package com.mht.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bus_aa01", "aaa001", BusAa01.class);
		arp.addMapping("bus_aa02", "aaa020", BusAa02.class);
		arp.addMapping("bus_aa03", "aaa030", BusAa03.class);
		arp.addMapping("bus_aa04", "aaa040", BusAa04.class);
		arp.addMapping("bus_aa99", "aaa001", BusAa99.class);
		arp.addMapping("bus_ba01", "aba001", BusBa01.class);
		arp.addMapping("bus_ba02", "aba020", BusBa02.class);
		arp.addMapping("bus_ba03", "aba030", BusBa03.class);
		arp.addMapping("bus_ba04", "aba040", BusBa04.class);
		arp.addMapping("bus_ba05", "aba050", BusBa05.class);
		arp.addMapping("bus_ba06", "aba060", BusBa06.class);
		arp.addMapping("bus_ba07", "aba070", BusBa07.class);
		arp.addMapping("bus_ba08", "aba080", BusBa08.class);
		arp.addMapping("bus_ba09", "aba090", BusBa09.class);
		arp.addMapping("bus_ca01", "aca010", BusCa01.class);
		arp.addMapping("bus_ca02", "aca001", BusCa02.class);
		arp.addMapping("bus_ca03", "aca030", BusCa03.class);
		arp.addMapping("bus_ca04", "aca040", BusCa04.class);
		arp.addMapping("bus_ca05", "aca050", BusCa05.class);
		arp.addMapping("bus_ca06", "aca060", BusCa06.class);
		arp.addMapping("bus_ca07", "aca070", BusCa07.class);
		arp.addMapping("bus_ca08", "aca080", BusCa08.class);
		arp.addMapping("bus_direction", "direction_id", BusDirection.class);
		arp.addMapping("bus_imgs", "aaa001", BusImgs.class);
		arp.addMapping("bus_info", "info_id", BusInfo.class);
		arp.addMapping("bus_order", "aca030", BusOrder.class);
		arp.addMapping("bus_pass", "pass_id", BusPass.class);
		arp.addMapping("bus_payinfo", "payInfo_id", BusPayinfo.class);
		arp.addMapping("bus_price", "aaa001", BusPrice.class);
		arp.addMapping("bus_token", "id", BusToken.class);
		arp.addMapping("bus_type", "type_id", BusType.class);
		arp.addMapping("car_direction", "direction_id", CarDirection.class);
		arp.addMapping("car_info", "info_id", CarInfo.class);
		arp.addMapping("car_info_pass", "info_pass_id", CarInfoPass.class);
		arp.addMapping("car_info_person", "route_person_id", CarInfoPerson.class);
		arp.addMapping("car_pass", "pass_id", CarPass.class);
		arp.addMapping("car_person", "person_id", CarPerson.class);
		arp.addMapping("car_route", "route_id", CarRoute.class);
		arp.addMapping("car_type", "type_id", CarType.class);
		arp.addMapping("comment_account", "acc_id", CommentAccount.class);
		arp.addMapping("comment_dept", "dept_id", CommentDept.class);
		arp.addMapping("comment_grade", "grade_id", CommentGrade.class);
		arp.addMapping("comment_proservice", "pros_id", CommentProservice.class);
		arp.addMapping("enroll_kindergarten", "kindergarten_id", EnrollKindergarten.class);
		arp.addMapping("enroll_middle_school", "middle_school_id", EnrollMiddleSchool.class);
		arp.addMapping("enroll_primary_school", "primary_school_id", EnrollPrimarySchool.class);
		arp.addMapping("fast_menu", "id", FastMenu.class);
		arp.addMapping("pm_detail", "detail_id", PmDetail.class);
		arp.addMapping("pm_field", "field_id", PmField.class);
		arp.addMapping("pm_index", "index_id", PmIndex.class);
		arp.addMapping("pm_link", "link_id", PmLink.class);
		arp.addMapping("pm_module", "module_id", PmModule.class);
		arp.addMapping("pm_table", "table_id", PmTable.class);
		arp.addMapping("pm_table_join", "join_id", PmTableJoin.class);
		arp.addMapping("pub_city", "city_id", PubCity.class);
		arp.addMapping("pub_country", "country_id", PubCountry.class);
		arp.addMapping("pub_edu_level", "level_id", PubEduLevel.class);
		arp.addMapping("pub_nation", "nation_id", PubNation.class);
		arp.addMapping("pub_province", "province_id", PubProvince.class);
		arp.addMapping("pub_town", "town_id", PubTown.class);
		arp.addMapping("return_zone_extend", "return_extend_id", ReturnZoneExtend.class);
		arp.addMapping("return_zone_materials_arrive", "zone_materials_arrive_id", ReturnZoneMaterialsArrive.class);
		arp.addMapping("return_zone_materials_bills", "zone_materials_bills_id", ReturnZoneMaterialsBills.class);
		arp.addMapping("return_zone_materials_details", "zone_materials_details_id", ReturnZoneMaterialsDetails.class);
		arp.addMapping("school_area", "school_area_id", SchoolArea.class);
		arp.addMapping("school_zone", "zone_id", SchoolZone.class);
		arp.addMapping("setting_item", "item_id", SettingItem.class);
		arp.addMapping("site_info", "site_id", SiteInfo.class);
		arp.addMapping("sms_info", "info_id", SmsInfo.class);
		arp.addMapping("sms_verify_code", "verify_code_id", SmsVerifyCode.class);
		arp.addMapping("stu_retreats", "id", StuRetreats.class);
		arp.addMapping("student_return_school_info", "return_school_info_id", StudentReturnSchoolInfo.class);
		arp.addMapping("sys_area", "id", SysArea.class);
		arp.addMapping("sys_code", "id", SysCode.class);
		arp.addMapping("sys_module", "module_id", SysModule.class);
		arp.addMapping("sys_perm", "perm_id", SysPerm.class);
		arp.addMapping("sys_plat", "plat_id", SysPlat.class);
		arp.addMapping("sys_role", "role_id", SysRole.class);
		arp.addMapping("sys_role_perm", "role_perm_id", SysRolePerm.class);
		// Composite Primary Key order: parent_site_id,role_id,site_id
		arp.addMapping("sys_role_site", "parent_site_id,role_id,site_id", SysRoleSite.class);
		arp.addMapping("sys_setting", "setting_id", SysSetting.class);
		arp.addMapping("sys_user", "user_id", SysUser.class);
		arp.addMapping("sys_user_perm", "user_perm_id", SysUserPerm.class);
		arp.addMapping("sys_user_role", "user_role_id", SysUserRole.class);
		arp.addMapping("teacher_return_school_info", "return_school_info_id", TeacherReturnSchoolInfo.class);
		arp.addMapping("test", "id", Test.class);
		arp.addMapping("tm_aa01", "aaa001", TmAa01.class);
		arp.addMapping("tm_aa02", "aaa020", TmAa02.class);
		arp.addMapping("tm_aa03", "aaa030", TmAa03.class);
		arp.addMapping("user_info", "info_id", UserInfo.class);
		arp.addMapping("weather", "weather_id", Weather.class);
		arp.addMapping("wechat_aa01", "aaa010", WechatAa01.class);
		arp.addMapping("wechat_aa02", "aaa020", WechatAa02.class);
		arp.addMapping("wechat_aa99", "aaa001", WechatAa99.class);
		arp.addMapping("wx_access_token", "access_token_id", WxAccessToken.class);
		arp.addMapping("xim_browse_record", "browse_record_id", XimBrowseRecord.class);
		arp.addMapping("xim_library", "library_id", XimLibrary.class);
		arp.addMapping("xim_login_log", "login_log_id", XimLoginLog.class);
		arp.addMapping("xim_menu", "qa_menu_id", XimMenu.class);
		arp.addMapping("xim_model", "model_id", XimModel.class);
		arp.addMapping("xim_ques_related", "ques_related_id", XimQuesRelated.class);
		arp.addMapping("xim_role_match", "match_id", XimRoleMatch.class);
		arp.addMapping("xim_setting", "xim_setting_id", XimSetting.class);
		arp.addMapping("zone_materials_info", "materials_info_id", ZoneMaterialsInfo.class);
		arp.addMapping("zone_materials_out_stock_arrive", "materials_out_stock_arrive_id", ZoneMaterialsOutStockArrive.class);
		arp.addMapping("zone_materials_out_stock_bills", "materials_out_stock_bills_id", ZoneMaterialsOutStockBills.class);
		arp.addMapping("zone_materials_out_stock_details", "materials_out_stock_details_id", ZoneMaterialsOutStockDetails.class);
		arp.addMapping("zone_out_extend", "zone_out_extend_id", ZoneOutExtend.class);
	}
}

