package com.mht.common.model;

import com.mht.common.model.base.BaseAlertSmsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlertSmsInfo extends BaseAlertSmsInfo<AlertSmsInfo> {
	public static final AlertSmsInfo dao = new AlertSmsInfo().dao();
}
