package com.mht.common.model;

import com.mht.common.model.base.BaseBusAa04;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusAa04 extends BaseBusAa04<BusAa04> {
	public static final BusAa04 dao = new BusAa04().dao();
}
