package com.mht.common.model;

import com.mht.common.model.base.BaseBusAa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusAa02 extends BaseBusAa02<BusAa02> {
	public static final BusAa02 dao = new BusAa02().dao();
}
