package com.mht.common.model;

import com.mht.common.model.base.BaseBusAa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusAa03 extends BaseBusAa03<BusAa03> {
	public static final BusAa03 dao = new BusAa03().dao();
}
