package com.mht.common.model;

import com.mht.common.model.base.BaseBusAa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusAa01 extends BaseBusAa01<BusAa01> {
	public static final BusAa01 dao = new BusAa01().dao();
}
