package com.mht.common.model;

import com.mht.common.model.base.BaseBusAa99;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusAa99 extends BaseBusAa99<BusAa99> {
	public static final BusAa99 dao = new BusAa99().dao();
}
