package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa08;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa08 extends BaseBusBa08<BusBa08> {
	public static final BusBa08 dao = new BusBa08().dao();
}
