package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa02 extends BaseBusBa02<BusBa02> {
	public static final BusBa02 dao = new BusBa02().dao();
}
