package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa05;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa05 extends BaseBusBa05<BusBa05> {
	public static final BusBa05 dao = new BusBa05().dao();
}
