package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa04;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa04 extends BaseBusBa04<BusBa04> {
	public static final BusBa04 dao = new BusBa04().dao();
}
