package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa09;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa09 extends BaseBusBa09<BusBa09> {
	public static final BusBa09 dao = new BusBa09().dao();
}
