package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa07;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa07 extends BaseBusBa07<BusBa07> {
	public static final BusBa07 dao = new BusBa07().dao();
}
