package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa03 extends BaseBusBa03<BusBa03> {
	public static final BusBa03 dao = new BusBa03().dao();
}
