package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa06;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa06 extends BaseBusBa06<BusBa06> {
	public static final BusBa06 dao = new BusBa06().dao();
}
