package com.mht.common.model;

import com.mht.common.model.base.BaseBusBa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusBa01 extends BaseBusBa01<BusBa01> {
	public static final BusBa01 dao = new BusBa01().dao();
}
