package com.mht.common.model;

import com.mht.common.model.base.BaseBusCa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusCa01 extends BaseBusCa01<BusCa01> {
	public static final BusCa01 dao = new BusCa01().dao();
}
