package com.mht.common.model;

import com.mht.common.model.base.BaseBusCa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusCa02 extends BaseBusCa02<BusCa02> {
	public static final BusCa02 dao = new BusCa02().dao();
}
