package com.mht.common.model;

import com.mht.common.model.base.BaseBusCa07;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusCa07 extends BaseBusCa07<BusCa07> {
	public static final BusCa07 dao = new BusCa07().dao();
}
