package com.mht.common.model;

import com.mht.common.model.base.BaseBusCa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusCa03 extends BaseBusCa03<BusCa03> {
	public static final BusCa03 dao = new BusCa03().dao();
}
