package com.mht.common.model;

import com.mht.common.model.base.BaseBusCa04;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusCa04 extends BaseBusCa04<BusCa04> {
	public static final BusCa04 dao = new BusCa04().dao();
}
