package com.mht.common.model;

import com.mht.common.model.base.BaseBusCa08;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusCa08 extends BaseBusCa08<BusCa08> {
	public static final BusCa08 dao = new BusCa08().dao();
}
