package com.mht.common.model;

import com.mht.common.model.base.BaseBusCa06;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusCa06 extends BaseBusCa06<BusCa06> {
	public static final BusCa06 dao = new BusCa06().dao();
}
