package com.mht.common.model;

import com.mht.common.model.base.BaseBusCa05;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusCa05 extends BaseBusCa05<BusCa05> {
	public static final BusCa05 dao = new BusCa05().dao();
}
