package com.mht.common.model;

import com.mht.common.model.base.BaseBusDirection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusDirection extends BaseBusDirection<BusDirection> {
	public static final BusDirection dao = new BusDirection().dao();
}
