package com.mht.common.model;

import com.mht.common.model.base.BaseBusInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusInfo extends BaseBusInfo<BusInfo> {
	public static final BusInfo dao = new BusInfo().dao();
}
