package com.mht.common.model;

import com.mht.common.model.base.BaseBusOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusOrder extends BaseBusOrder<BusOrder> {
	public static final BusOrder dao = new BusOrder().dao();
}
