package com.mht.common.model;

import com.mht.common.model.base.BaseBusPayinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusPayinfo extends BaseBusPayinfo<BusPayinfo> {
	public static final BusPayinfo dao = new BusPayinfo().dao();
}
