package com.mht.common.model;

import com.mht.common.model.base.BaseBusPass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusPass extends BaseBusPass<BusPass> {
	public static final BusPass dao = new BusPass().dao();
}
