package com.mht.common.model;

import com.mht.common.model.base.BaseBusToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusToken extends BaseBusToken<BusToken> {
	public static final BusToken dao = new BusToken().dao();
}
