package com.mht.common.model;

import com.mht.common.model.base.BaseBusType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusType extends BaseBusType<BusType> {
	public static final BusType dao = new BusType().dao();
}
