package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa04;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa04 extends BaseCanteenAa04<CanteenAa04> {
	public static final CanteenAa04 dao = new CanteenAa04().dao();
}
