package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenMc03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenMc03 extends BaseCanteenMc03<CanteenMc03> {
	public static final CanteenMc03 dao = new CanteenMc03().dao();
}
