package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenTp02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenTp02 extends BaseCanteenTp02<CanteenTp02> {
	public static final CanteenTp02 dao = new CanteenTp02().dao();
}
