package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa09;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa09 extends BaseCanteenBa09<CanteenBa09> {
	public static final CanteenBa09 dao = new CanteenBa09().dao();
}
