package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa09;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa09 extends BaseCanteenAa09<CanteenAa09> {
	public static final CanteenAa09 dao = new CanteenAa09().dao();
}
