package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenMc06;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenMc06 extends BaseCanteenMc06<CanteenMc06> {
	public static final CanteenMc06 dao = new CanteenMc06().dao();
}
