package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenSu01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenSu01 extends BaseCanteenSu01<CanteenSu01> {
	public static final CanteenSu01 dao = new CanteenSu01().dao();
}
