package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenMc02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenMc02 extends BaseCanteenMc02<CanteenMc02> {
	public static final CanteenMc02 dao = new CanteenMc02().dao();
}
