package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa11;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa11 extends BaseCanteenCa11<CanteenCa11> {
	public static final CanteenCa11 dao = new CanteenCa11().dao();
}
