package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa10;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa10 extends BaseCanteenAa10<CanteenAa10> {
	public static final CanteenAa10 dao = new CanteenAa10().dao();
}
