package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa05;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa05 extends BaseCanteenCa05<CanteenCa05> {
	public static final CanteenCa05 dao = new CanteenCa05().dao();
}
