package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa08;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa08 extends BaseCanteenCa08<CanteenCa08> {
	public static final CanteenCa08 dao = new CanteenCa08().dao();
}
