package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa06;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa06 extends BaseCanteenAa06<CanteenAa06> {
	public static final CanteenAa06 dao = new CanteenAa06().dao();
}
