package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa06;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa06 extends BaseCanteenCa06<CanteenCa06> {
	public static final CanteenCa06 dao = new CanteenCa06().dao();
}
