package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa99;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa99 extends BaseCanteenAa99<CanteenAa99> {
	public static final CanteenAa99 dao = new CanteenAa99().dao();
}
