package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa15;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa15 extends BaseCanteenAa15<CanteenAa15> {
	public static final CanteenAa15 dao = new CanteenAa15().dao();
}
