package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenSu02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenSu02 extends BaseCanteenSu02<CanteenSu02> {
	public static final CanteenSu02 dao = new CanteenSu02().dao();
}
