package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa13;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa13 extends BaseCanteenAa13<CanteenAa13> {
	public static final CanteenAa13 dao = new CanteenAa13().dao();
}
