package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa02Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa02Temp extends BaseCanteenBa02Temp<CanteenBa02Temp> {
	public static final CanteenBa02Temp dao = new CanteenBa02Temp().dao();
}
