package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenMc01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenMc01 extends BaseCanteenMc01<CanteenMc01> {
	public static final CanteenMc01 dao = new CanteenMc01().dao();
}
