package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa08;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa08 extends BaseCanteenAa08<CanteenAa08> {
	public static final CanteenAa08 dao = new CanteenAa08().dao();
}
