package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa07;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa07 extends BaseCanteenAa07<CanteenAa07> {
	public static final CanteenAa07 dao = new CanteenAa07().dao();
}
