package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa10;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa10 extends BaseCanteenCa10<CanteenCa10> {
	public static final CanteenCa10 dao = new CanteenCa10().dao();
}
