package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa04;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa04 extends BaseCanteenBa04<CanteenBa04> {
	public static final CanteenBa04 dao = new CanteenBa04().dao();
}
