package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa12;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa12 extends BaseCanteenAa12<CanteenAa12> {
	public static final CanteenAa12 dao = new CanteenAa12().dao();
}
