package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa05;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa05 extends BaseCanteenAa05<CanteenAa05> {
	public static final CanteenAa05 dao = new CanteenAa05().dao();
}
