package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa06;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa06 extends BaseCanteenBa06<CanteenBa06> {
	public static final CanteenBa06 dao = new CanteenBa06().dao();
}
