package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa03 extends BaseCanteenBa03<CanteenBa03> {
	public static final CanteenBa03 dao = new CanteenBa03().dao();
}
