package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa02 extends BaseCanteenCa02<CanteenCa02> {
	public static final CanteenCa02 dao = new CanteenCa02().dao();
}
