package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa03 extends BaseCanteenCa03<CanteenCa03> {
	public static final CanteenCa03 dao = new CanteenCa03().dao();
}
