package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa98;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa98 extends BaseCanteenAa98<CanteenAa98> {
	public static final CanteenAa98 dao = new CanteenAa98().dao();
}
