package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa01 extends BaseCanteenBa01<CanteenBa01> {
	public static final CanteenBa01 dao = new CanteenBa01().dao();
}
