package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa14;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa14 extends BaseCanteenAa14<CanteenAa14> {
	public static final CanteenAa14 dao = new CanteenAa14().dao();
}
