package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa03 extends BaseCanteenAa03<CanteenAa03> {
	public static final CanteenAa03 dao = new CanteenAa03().dao();
}
