package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa17;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa17 extends BaseCanteenAa17<CanteenAa17> {
	public static final CanteenAa17 dao = new CanteenAa17().dao();
}
