package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa02 extends BaseCanteenBa02<CanteenBa02> {
	public static final CanteenBa02 dao = new CanteenBa02().dao();
}
