package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa01 extends BaseCanteenCa01<CanteenCa01> {
	public static final CanteenCa01 dao = new CanteenCa01().dao();
}
