package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa08;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa08 extends BaseCanteenBa08<CanteenBa08> {
	public static final CanteenBa08 dao = new CanteenBa08().dao();
}
