package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenTp01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenTp01 extends BaseCanteenTp01<CanteenTp01> {
	public static final CanteenTp01 dao = new CanteenTp01().dao();
}
