package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa02 extends BaseCanteenAa02<CanteenAa02> {
	public static final CanteenAa02 dao = new CanteenAa02().dao();
}
