package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa16;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa16 extends BaseCanteenAa16<CanteenAa16> {
	public static final CanteenAa16 dao = new CanteenAa16().dao();
}
