package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa04;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa04 extends BaseCanteenCa04<CanteenCa04> {
	public static final CanteenCa04 dao = new CanteenCa04().dao();
}
