package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa07;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa07 extends BaseCanteenCa07<CanteenCa07> {
	public static final CanteenCa07 dao = new CanteenCa07().dao();
}
