package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenAa11;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenAa11 extends BaseCanteenAa11<CanteenAa11> {
	public static final CanteenAa11 dao = new CanteenAa11().dao();
}
