package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenMc04;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenMc04 extends BaseCanteenMc04<CanteenMc04> {
	public static final CanteenMc04 dao = new CanteenMc04().dao();
}
