package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenBa05;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenBa05 extends BaseCanteenBa05<CanteenBa05> {
	public static final CanteenBa05 dao = new CanteenBa05().dao();
}
