package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenMc05;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenMc05 extends BaseCanteenMc05<CanteenMc05> {
	public static final CanteenMc05 dao = new CanteenMc05().dao();
}
