package com.mht.common.model;

import com.mht.common.model.base.BaseCanteenCa09;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CanteenCa09 extends BaseCanteenCa09<CanteenCa09> {
	public static final CanteenCa09 dao = new CanteenCa09().dao();
}
