package com.mht.common.model;

import com.mht.common.model.base.BaseCarDirection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarDirection extends BaseCarDirection<CarDirection> {
	public static final CarDirection dao = new CarDirection().dao();
}
