package com.mht.common.model;

import com.mht.common.model.base.BaseCarInfoPass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarInfoPass extends BaseCarInfoPass<CarInfoPass> {
	public static final CarInfoPass dao = new CarInfoPass().dao();
}
