package com.mht.common.model;

import com.mht.common.model.base.BaseCarInfoPerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarInfoPerson extends BaseCarInfoPerson<CarInfoPerson> {
	public static final CarInfoPerson dao = new CarInfoPerson().dao();
}
