package com.mht.common.model;

import com.mht.common.model.base.BaseCarInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarInfo extends BaseCarInfo<CarInfo> {
	public static final CarInfo dao = new CarInfo().dao();
}
