package com.mht.common.model;

import com.mht.common.model.base.BaseCarPass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarPass extends BaseCarPass<CarPass> {
	public static final CarPass dao = new CarPass().dao();
}
