package com.mht.common.model;

import com.mht.common.model.base.BaseCarPerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarPerson extends BaseCarPerson<CarPerson> {
	public static final CarPerson dao = new CarPerson().dao();
}
