package com.mht.common.model;

import com.mht.common.model.base.BaseCarRoute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarRoute extends BaseCarRoute<CarRoute> {
	public static final CarRoute dao = new CarRoute().dao();
}
