package com.mht.common.model;

import com.mht.common.model.base.BaseCarType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarType extends BaseCarType<CarType> {
	public static final CarType dao = new CarType().dao();
}
