package com.mht.common.model;

import com.mht.common.model.base.BaseCommentsInvestigation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentsInvestigation extends BaseCommentsInvestigation<CommentsInvestigation> {
	public static final CommentsInvestigation dao = new CommentsInvestigation().dao();
}
