package com.mht.common.model;

import com.mht.common.model.base.BaseCommentTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentTopic extends BaseCommentTopic<CommentTopic> {
	public static final CommentTopic dao = new CommentTopic().dao();
}
