package com.mht.common.model;

import com.mht.common.model.base.BaseCommentReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentReply extends BaseCommentReply<CommentReply> {
	public static final CommentReply dao = new CommentReply().dao();
}
