package com.mht.common.model;

import com.mht.common.model.base.BaseCommentDeploy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentDeploy extends BaseCommentDeploy<CommentDeploy> {
	public static final CommentDeploy dao = new CommentDeploy().dao();
}
