package com.mht.common.model;

import com.mht.common.model.base.BaseCommentsDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentsDept extends BaseCommentsDept<CommentsDept> {
	public static final CommentsDept dao = new CommentsDept().dao();
}
