package com.mht.common.model;

import com.mht.common.model.base.BaseCommentAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentAccount extends BaseCommentAccount<CommentAccount> {
	public static final CommentAccount dao = new CommentAccount().dao();
}
