package com.mht.common.model;

import com.mht.common.model.base.BaseCommentsTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentsTopic extends BaseCommentsTopic<CommentsTopic> {
	public static final CommentsTopic dao = new CommentsTopic().dao();
}
