package com.mht.common.model;

import com.mht.common.model.base.BaseCommentPassport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentPassport extends BaseCommentPassport<CommentPassport> {
	public static final CommentPassport dao = new CommentPassport().dao();
}
