package com.mht.common.model;

import com.mht.common.model.base.BaseCommentProservice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentProservice extends BaseCommentProservice<CommentProservice> {
	public static final CommentProservice dao = new CommentProservice().dao();
}
