package com.mht.common.model;

import com.mht.common.model.base.BaseCommentsProposal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentsProposal extends BaseCommentsProposal<CommentsProposal> {
	public static final CommentsProposal dao = new CommentsProposal().dao();
}
