package com.mht.common.model;

import com.mht.common.model.base.BaseCommentRand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentRand extends BaseCommentRand<CommentRand> {
	public static final CommentRand dao = new CommentRand().dao();
}
