package com.mht.common.model;

import com.mht.common.model.base.BaseCommentsZone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentsZone extends BaseCommentsZone<CommentsZone> {
	public static final CommentsZone dao = new CommentsZone().dao();
}
