package com.mht.common.model;

import com.mht.common.model.base.BaseCommentWjdc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentWjdc extends BaseCommentWjdc<CommentWjdc> {
	public static final CommentWjdc dao = new CommentWjdc().dao();
}
