package com.mht.common.model;

import com.mht.common.model.base.BaseCommentDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentDept extends BaseCommentDept<CommentDept> {
	public static final CommentDept dao = new CommentDept().dao();
}
