package com.mht.common.model;

import com.mht.common.model.base.BaseCommentsUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentsUser extends BaseCommentsUser<CommentsUser> {
	public static final CommentsUser dao = new CommentsUser().dao();
}
