package com.mht.common.model;

import com.mht.common.model.base.BaseCommentCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentCategory extends BaseCommentCategory<CommentCategory> {
	public static final CommentCategory dao = new CommentCategory().dao();
}
