package com.mht.common.model;

import com.mht.common.model.base.BaseCommentYjjy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentYjjy extends BaseCommentYjjy<CommentYjjy> {
	public static final CommentYjjy dao = new CommentYjjy().dao();
}
