package com.mht.common.model;

import com.mht.common.model.base.BaseCommentCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentCode extends BaseCommentCode<CommentCode> {
	public static final CommentCode dao = new CommentCode().dao();
}
