package com.mht.common.model;

import com.mht.common.model.base.BaseCommentLaud;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentLaud extends BaseCommentLaud<CommentLaud> {
	public static final CommentLaud dao = new CommentLaud().dao();
}
