package com.mht.common.model;

import com.mht.common.model.base.BaseCommentsOption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentsOption extends BaseCommentsOption<CommentsOption> {
	public static final CommentsOption dao = new CommentsOption().dao();
}
