package com.mht.common.model;

import com.mht.common.model.base.BaseCommentSitive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentSitive extends BaseCommentSitive<CommentSitive> {
	public static final CommentSitive dao = new CommentSitive().dao();
}
