package com.mht.common.model;

import com.mht.common.model.base.BaseCommentWjdcxx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentWjdcxx extends BaseCommentWjdcxx<CommentWjdcxx> {
	public static final CommentWjdcxx dao = new CommentWjdcxx().dao();
}
