package com.mht.common.model;

import com.mht.common.model.base.BaseCommentGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentGrade extends BaseCommentGrade<CommentGrade> {
	public static final CommentGrade dao = new CommentGrade().dao();
}
