package com.mht.common.model;

import com.mht.common.model.base.BaseDepartmentApplyMaterialsArrive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentApplyMaterialsArrive extends BaseDepartmentApplyMaterialsArrive<DepartmentApplyMaterialsArrive> {
	public static final DepartmentApplyMaterialsArrive dao = new DepartmentApplyMaterialsArrive().dao();
}
