package com.mht.common.model;

import com.mht.common.model.base.BaseDepartmentMaterialsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentMaterialsInfo extends BaseDepartmentMaterialsInfo<DepartmentMaterialsInfo> {
	public static final DepartmentMaterialsInfo dao = new DepartmentMaterialsInfo().dao();
}
