package com.mht.common.model;

import com.mht.common.model.base.BaseDepartmentApplyMaterialsBills;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentApplyMaterialsBills extends BaseDepartmentApplyMaterialsBills<DepartmentApplyMaterialsBills> {
	public static final DepartmentApplyMaterialsBills dao = new DepartmentApplyMaterialsBills().dao();
}
