package com.mht.common.model;

import com.mht.common.model.base.BaseDepartmentMaterialsOutStockDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentMaterialsOutStockDetails extends BaseDepartmentMaterialsOutStockDetails<DepartmentMaterialsOutStockDetails> {
	public static final DepartmentMaterialsOutStockDetails dao = new DepartmentMaterialsOutStockDetails().dao();
}
