package com.mht.common.model;

import com.mht.common.model.base.BaseDepartmentRecoverMaterialsDetialsArrive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentRecoverMaterialsDetialsArrive extends BaseDepartmentRecoverMaterialsDetialsArrive<DepartmentRecoverMaterialsDetialsArrive> {
	public static final DepartmentRecoverMaterialsDetialsArrive dao = new DepartmentRecoverMaterialsDetialsArrive().dao();
}
