package com.mht.common.model;

import com.mht.common.model.base.BaseDepartmentApplyMaterialsDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentApplyMaterialsDetails extends BaseDepartmentApplyMaterialsDetails<DepartmentApplyMaterialsDetails> {
	public static final DepartmentApplyMaterialsDetails dao = new DepartmentApplyMaterialsDetails().dao();
}
