package com.mht.common.model;

import com.mht.common.model.base.BaseDepartmentApplyExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentApplyExtend extends BaseDepartmentApplyExtend<DepartmentApplyExtend> {
	public static final DepartmentApplyExtend dao = new DepartmentApplyExtend().dao();
}
