package com.mht.common.model;

import com.mht.common.model.base.BaseDepartmentMaterialsOutStockBills;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentMaterialsOutStockBills extends BaseDepartmentMaterialsOutStockBills<DepartmentMaterialsOutStockBills> {
	public static final DepartmentMaterialsOutStockBills dao = new DepartmentMaterialsOutStockBills().dao();
}
