package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAa03 extends BaseDormitoryAa03<DormitoryAa03> {
	public static final DormitoryAa03 dao = new DormitoryAa03().dao();
}
