package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCompensatePaymentRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCompensatePaymentRecords extends BaseDormitoryCompensatePaymentRecords<DormitoryCompensatePaymentRecords> {
	public static final DormitoryCompensatePaymentRecords dao = new DormitoryCompensatePaymentRecords().dao();
}
