package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAllotRoomPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAllotRoomPlan extends BaseDormitoryAllotRoomPlan<DormitoryAllotRoomPlan> {
	public static final DormitoryAllotRoomPlan dao = new DormitoryAllotRoomPlan().dao();
}
