package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryBd01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryBd01 extends BaseDormitoryBd01<DormitoryBd01> {
	public static final DormitoryBd01 dao = new DormitoryBd01().dao();
}
