package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAdjustApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAdjustApply extends BaseDormitoryAdjustApply<DormitoryAdjustApply> {
	public static final DormitoryAdjustApply dao = new DormitoryAdjustApply().dao();
}
