package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCounselorVisite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCounselorVisite extends BaseDormitoryCounselorVisite<DormitoryCounselorVisite> {
	public static final DormitoryCounselorVisite dao = new DormitoryCounselorVisite().dao();
}
