package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryStyleLikeRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryStyleLikeRecord extends BaseDormitoryStyleLikeRecord<DormitoryStyleLikeRecord> {
	public static final DormitoryStyleLikeRecord dao = new DormitoryStyleLikeRecord().dao();
}
