package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryActivity extends BaseDormitoryActivity<DormitoryActivity> {
	public static final DormitoryActivity dao = new DormitoryActivity().dao();
}
