package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryBaseInfoTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryBaseInfoTemp extends BaseDormitoryBaseInfoTemp<DormitoryBaseInfoTemp> {
	public static final DormitoryBaseInfoTemp dao = new DormitoryBaseInfoTemp().dao();
}
