package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAllotChooseRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAllotChooseRecord extends BaseDormitoryAllotChooseRecord<DormitoryAllotChooseRecord> {
	public static final DormitoryAllotChooseRecord dao = new DormitoryAllotChooseRecord().dao();
}
