package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryTemporaryRenew;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryTemporaryRenew extends BaseDormitoryTemporaryRenew<DormitoryTemporaryRenew> {
	public static final DormitoryTemporaryRenew dao = new DormitoryTemporaryRenew().dao();
}
