package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryDeviceMaintenance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryDeviceMaintenance extends BaseDormitoryDeviceMaintenance<DormitoryDeviceMaintenance> {
	public static final DormitoryDeviceMaintenance dao = new DormitoryDeviceMaintenance().dao();
}
