package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCheckRoomDate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCheckRoomDate extends BaseDormitoryCheckRoomDate<DormitoryCheckRoomDate> {
	public static final DormitoryCheckRoomDate dao = new DormitoryCheckRoomDate().dao();
}
