package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryHealthEvaluationSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryHealthEvaluationSetting extends BaseDormitoryHealthEvaluationSetting<DormitoryHealthEvaluationSetting> {
	public static final DormitoryHealthEvaluationSetting dao = new DormitoryHealthEvaluationSetting().dao();
}
