package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryStandard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryStandard extends BaseDormitoryStandard<DormitoryStandard> {
	public static final DormitoryStandard dao = new DormitoryStandard().dao();
}
