package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryGroup extends BaseDormitoryGroup<DormitoryGroup> {
	public static final DormitoryGroup dao = new DormitoryGroup().dao();
}
