package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryActivityEvaluate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryActivityEvaluate extends BaseDormitoryActivityEvaluate<DormitoryActivityEvaluate> {
	public static final DormitoryActivityEvaluate dao = new DormitoryActivityEvaluate().dao();
}
