package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryLoseRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryLoseRecord extends BaseDormitoryLoseRecord<DormitoryLoseRecord> {
	public static final DormitoryLoseRecord dao = new DormitoryLoseRecord().dao();
}
