package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryChooseMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryChooseMessage extends BaseDormitoryChooseMessage<DormitoryChooseMessage> {
	public static final DormitoryChooseMessage dao = new DormitoryChooseMessage().dao();
}
