package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryFloor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryFloor extends BaseDormitoryFloor<DormitoryFloor> {
	public static final DormitoryFloor dao = new DormitoryFloor().dao();
}
