package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCa03Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCa03Temp extends BaseDormitoryCa03Temp<DormitoryCa03Temp> {
	public static final DormitoryCa03Temp dao = new DormitoryCa03Temp().dao();
}
