package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryFirehydrant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryFirehydrant extends BaseDormitoryFirehydrant<DormitoryFirehydrant> {
	public static final DormitoryFirehydrant dao = new DormitoryFirehydrant().dao();
}
