package com.mht.common.model;

import com.mht.common.model.base.BaseDormitorySecuritycheck;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitorySecuritycheck extends BaseDormitorySecuritycheck<DormitorySecuritycheck> {
	public static final DormitorySecuritycheck dao = new DormitorySecuritycheck().dao();
}
