package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCa02 extends BaseDormitoryCa02<DormitoryCa02> {
	public static final DormitoryCa02 dao = new DormitoryCa02().dao();
}
