package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryTowerFacilities;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryTowerFacilities extends BaseDormitoryTowerFacilities<DormitoryTowerFacilities> {
	public static final DormitoryTowerFacilities dao = new DormitoryTowerFacilities().dao();
}
