package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAb02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAb02 extends BaseDormitoryAb02<DormitoryAb02> {
	public static final DormitoryAb02 dao = new DormitoryAb02().dao();
}
