package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAa01 extends BaseDormitoryAa01<DormitoryAa01> {
	public static final DormitoryAa01 dao = new DormitoryAa01().dao();
}
