package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryDepartmentTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryDepartmentTemp extends BaseDormitoryDepartmentTemp<DormitoryDepartmentTemp> {
	public static final DormitoryDepartmentTemp dao = new DormitoryDepartmentTemp().dao();
}
