package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryLoveRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryLoveRoom extends BaseDormitoryLoveRoom<DormitoryLoveRoom> {
	public static final DormitoryLoveRoom dao = new DormitoryLoveRoom().dao();
}
