package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCounsellorAdjustRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCounsellorAdjustRoom extends BaseDormitoryCounsellorAdjustRoom<DormitoryCounsellorAdjustRoom> {
	public static final DormitoryCounsellorAdjustRoom dao = new DormitoryCounsellorAdjustRoom().dao();
}
