package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCa03 extends BaseDormitoryCa03<DormitoryCa03> {
	public static final DormitoryCa03 dao = new DormitoryCa03().dao();
}
