package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryStudent extends BaseDormitoryStudent<DormitoryStudent> {
	public static final DormitoryStudent dao = new DormitoryStudent().dao();
}
