package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryClass extends BaseDormitoryClass<DormitoryClass> {
	public static final DormitoryClass dao = new DormitoryClass().dao();
}
