package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryGoodsEntryExit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryGoodsEntryExit extends BaseDormitoryGoodsEntryExit<DormitoryGoodsEntryExit> {
	public static final DormitoryGoodsEntryExit dao = new DormitoryGoodsEntryExit().dao();
}
