package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryHealthEvaluationScoreItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryHealthEvaluationScoreItem extends BaseDormitoryHealthEvaluationScoreItem<DormitoryHealthEvaluationScoreItem> {
	public static final DormitoryHealthEvaluationScoreItem dao = new DormitoryHealthEvaluationScoreItem().dao();
}
