package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAb01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAb01 extends BaseDormitoryAb01<DormitoryAb01> {
	public static final DormitoryAb01 dao = new DormitoryAb01().dao();
}
