package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryApproval;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryApproval extends BaseDormitoryApproval<DormitoryApproval> {
	public static final DormitoryApproval dao = new DormitoryApproval().dao();
}
