package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCheckPaymentRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCheckPaymentRecords extends BaseDormitoryCheckPaymentRecords<DormitoryCheckPaymentRecords> {
	public static final DormitoryCheckPaymentRecords dao = new DormitoryCheckPaymentRecords().dao();
}
