package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryKeyBorrow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryKeyBorrow extends BaseDormitoryKeyBorrow<DormitoryKeyBorrow> {
	public static final DormitoryKeyBorrow dao = new DormitoryKeyBorrow().dao();
}
