package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryHealthEvaluation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryHealthEvaluation extends BaseDormitoryHealthEvaluation<DormitoryHealthEvaluation> {
	public static final DormitoryHealthEvaluation dao = new DormitoryHealthEvaluation().dao();
}
