package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCheckOutTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCheckOutTemp extends BaseDormitoryCheckOutTemp<DormitoryCheckOutTemp> {
	public static final DormitoryCheckOutTemp dao = new DormitoryCheckOutTemp().dao();
}
