package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryActivityRoomApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryActivityRoomApply extends BaseDormitoryActivityRoomApply<DormitoryActivityRoomApply> {
	public static final DormitoryActivityRoomApply dao = new DormitoryActivityRoomApply().dao();
}
