package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryHealthEvaluationItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryHealthEvaluationItem extends BaseDormitoryHealthEvaluationItem<DormitoryHealthEvaluationItem> {
	public static final DormitoryHealthEvaluationItem dao = new DormitoryHealthEvaluationItem().dao();
}
