package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryGoodsDamageRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryGoodsDamageRecord extends BaseDormitoryGoodsDamageRecord<DormitoryGoodsDamageRecord> {
	public static final DormitoryGoodsDamageRecord dao = new DormitoryGoodsDamageRecord().dao();
}
