package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryNoonBreakAppraise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryNoonBreakAppraise extends BaseDormitoryNoonBreakAppraise<DormitoryNoonBreakAppraise> {
	public static final DormitoryNoonBreakAppraise dao = new DormitoryNoonBreakAppraise().dao();
}
