package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryTemporary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryTemporary extends BaseDormitoryTemporary<DormitoryTemporary> {
	public static final DormitoryTemporary dao = new DormitoryTemporary().dao();
}
