package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryLateinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryLateinfo extends BaseDormitoryLateinfo<DormitoryLateinfo> {
	public static final DormitoryLateinfo dao = new DormitoryLateinfo().dao();
}
