package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCounsellor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCounsellor extends BaseDormitoryCounsellor<DormitoryCounsellor> {
	public static final DormitoryCounsellor dao = new DormitoryCounsellor().dao();
}
