package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryVisitor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryVisitor extends BaseDormitoryVisitor<DormitoryVisitor> {
	public static final DormitoryVisitor dao = new DormitoryVisitor().dao();
}
