package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryStudentCheckIn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryStudentCheckIn extends BaseDormitoryStudentCheckIn<DormitoryStudentCheckIn> {
	public static final DormitoryStudentCheckIn dao = new DormitoryStudentCheckIn().dao();
}
