package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCa04;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCa04 extends BaseDormitoryCa04<DormitoryCa04> {
	public static final DormitoryCa04 dao = new DormitoryCa04().dao();
}
