package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryRule extends BaseDormitoryRule<DormitoryRule> {
	public static final DormitoryRule dao = new DormitoryRule().dao();
}
