package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryHealthEvaluationScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryHealthEvaluationScore extends BaseDormitoryHealthEvaluationScore<DormitoryHealthEvaluationScore> {
	public static final DormitoryHealthEvaluationScore dao = new DormitoryHealthEvaluationScore().dao();
}
