package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryEvaluationActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryEvaluationActivity extends BaseDormitoryEvaluationActivity<DormitoryEvaluationActivity> {
	public static final DormitoryEvaluationActivity dao = new DormitoryEvaluationActivity().dao();
}
