package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryTemporaryCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryTemporaryCharge extends BaseDormitoryTemporaryCharge<DormitoryTemporaryCharge> {
	public static final DormitoryTemporaryCharge dao = new DormitoryTemporaryCharge().dao();
}
