package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCode extends BaseDormitoryCode<DormitoryCode> {
	public static final DormitoryCode dao = new DormitoryCode().dao();
}
