package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryRoomCoords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryRoomCoords extends BaseDormitoryRoomCoords<DormitoryRoomCoords> {
	public static final DormitoryRoomCoords dao = new DormitoryRoomCoords().dao();
}
