package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryRoomTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryRoomTemp extends BaseDormitoryRoomTemp<DormitoryRoomTemp> {
	public static final DormitoryRoomTemp dao = new DormitoryRoomTemp().dao();
}
