package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryTower;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryTower extends BaseDormitoryTower<DormitoryTower> {
	public static final DormitoryTower dao = new DormitoryTower().dao();
}
