package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryRoom extends BaseDormitoryRoom<DormitoryRoom> {
	public static final DormitoryRoom dao = new DormitoryRoom().dao();
}
