package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCounsellorTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCounsellorTemp extends BaseDormitoryCounsellorTemp<DormitoryCounsellorTemp> {
	public static final DormitoryCounsellorTemp dao = new DormitoryCounsellorTemp().dao();
}
