package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCheckInAgain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCheckInAgain extends BaseDormitoryCheckInAgain<DormitoryCheckInAgain> {
	public static final DormitoryCheckInAgain dao = new DormitoryCheckInAgain().dao();
}
