package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryBuildingPatrol;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryBuildingPatrol extends BaseDormitoryBuildingPatrol<DormitoryBuildingPatrol> {
	public static final DormitoryBuildingPatrol dao = new DormitoryBuildingPatrol().dao();
}
