package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryMajorTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryMajorTemp extends BaseDormitoryMajorTemp<DormitoryMajorTemp> {
	public static final DormitoryMajorTemp dao = new DormitoryMajorTemp().dao();
}
