package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryNoonBreakOutRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryNoonBreakOutRoom extends BaseDormitoryNoonBreakOutRoom<DormitoryNoonBreakOutRoom> {
	public static final DormitoryNoonBreakOutRoom dao = new DormitoryNoonBreakOutRoom().dao();
}
