package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryStudentCheckInTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryStudentCheckInTemp extends BaseDormitoryStudentCheckInTemp<DormitoryStudentCheckInTemp> {
	public static final DormitoryStudentCheckInTemp dao = new DormitoryStudentCheckInTemp().dao();
}
