package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryClassTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryClassTemp extends BaseDormitoryClassTemp<DormitoryClassTemp> {
	public static final DormitoryClassTemp dao = new DormitoryClassTemp().dao();
}
