package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryTemporaryOutRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryTemporaryOutRoom extends BaseDormitoryTemporaryOutRoom<DormitoryTemporaryOutRoom> {
	public static final DormitoryTemporaryOutRoom dao = new DormitoryTemporaryOutRoom().dao();
}
