package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCa01 extends BaseDormitoryCa01<DormitoryCa01> {
	public static final DormitoryCa01 dao = new DormitoryCa01().dao();
}
