package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryTemporaryAllotmentRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryTemporaryAllotmentRoom extends BaseDormitoryTemporaryAllotmentRoom<DormitoryTemporaryAllotmentRoom> {
	public static final DormitoryTemporaryAllotmentRoom dao = new DormitoryTemporaryAllotmentRoom().dao();
}
