package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryBed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryBed extends BaseDormitoryBed<DormitoryBed> {
	public static final DormitoryBed dao = new DormitoryBed().dao();
}
