package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAllotChooseTemporary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAllotChooseTemporary extends BaseDormitoryAllotChooseTemporary<DormitoryAllotChooseTemporary> {
	public static final DormitoryAllotChooseTemporary dao = new DormitoryAllotChooseTemporary().dao();
}
