package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryStyle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryStyle extends BaseDormitoryStyle<DormitoryStyle> {
	public static final DormitoryStyle dao = new DormitoryStyle().dao();
}
