package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAdjust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAdjust extends BaseDormitoryAdjust<DormitoryAdjust> {
	public static final DormitoryAdjust dao = new DormitoryAdjust().dao();
}
