package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryHealthEvaluationTower;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryHealthEvaluationTower extends BaseDormitoryHealthEvaluationTower<DormitoryHealthEvaluationTower> {
	public static final DormitoryHealthEvaluationTower dao = new DormitoryHealthEvaluationTower().dao();
}
