package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryBb01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryBb01 extends BaseDormitoryBb01<DormitoryBb01> {
	public static final DormitoryBb01 dao = new DormitoryBb01().dao();
}
