package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAllotSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAllotSetting extends BaseDormitoryAllotSetting<DormitoryAllotSetting> {
	public static final DormitoryAllotSetting dao = new DormitoryAllotSetting().dao();
}
