package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryNoonBreak;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryNoonBreak extends BaseDormitoryNoonBreak<DormitoryNoonBreak> {
	public static final DormitoryNoonBreak dao = new DormitoryNoonBreak().dao();
}
