package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCounsellorInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCounsellorInfo extends BaseDormitoryCounsellorInfo<DormitoryCounsellorInfo> {
	public static final DormitoryCounsellorInfo dao = new DormitoryCounsellorInfo().dao();
}
