package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAa02 extends BaseDormitoryAa02<DormitoryAa02> {
	public static final DormitoryAa02 dao = new DormitoryAa02().dao();
}
