package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryViolateRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryViolateRecord extends BaseDormitoryViolateRecord<DormitoryViolateRecord> {
	public static final DormitoryViolateRecord dao = new DormitoryViolateRecord().dao();
}
