package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCheckOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCheckOut extends BaseDormitoryCheckOut<DormitoryCheckOut> {
	public static final DormitoryCheckOut dao = new DormitoryCheckOut().dao();
}
