package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryMajor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryMajor extends BaseDormitoryMajor<DormitoryMajor> {
	public static final DormitoryMajor dao = new DormitoryMajor().dao();
}
