package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCounsellorCheckIn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCounsellorCheckIn extends BaseDormitoryCounsellorCheckIn<DormitoryCounsellorCheckIn> {
	public static final DormitoryCounsellorCheckIn dao = new DormitoryCounsellorCheckIn().dao();
}
