package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryIllegalElectric;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryIllegalElectric extends BaseDormitoryIllegalElectric<DormitoryIllegalElectric> {
	public static final DormitoryIllegalElectric dao = new DormitoryIllegalElectric().dao();
}
