package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryDepartment extends BaseDormitoryDepartment<DormitoryDepartment> {
	public static final DormitoryDepartment dao = new DormitoryDepartment().dao();
}
