package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryCancelCheckIn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryCancelCheckIn extends BaseDormitoryCancelCheckIn<DormitoryCancelCheckIn> {
	public static final DormitoryCancelCheckIn dao = new DormitoryCancelCheckIn().dao();
}
