package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryStudentTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryStudentTemp extends BaseDormitoryStudentTemp<DormitoryStudentTemp> {
	public static final DormitoryStudentTemp dao = new DormitoryStudentTemp().dao();
}
