package com.mht.common.model;

import com.mht.common.model.base.BaseDormitorySanitarySecurityScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitorySanitarySecurityScore extends BaseDormitorySanitarySecurityScore<DormitorySanitarySecurityScore> {
	public static final DormitorySanitarySecurityScore dao = new DormitorySanitarySecurityScore().dao();
}
