package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryInspectionActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryInspectionActivity extends BaseDormitoryInspectionActivity<DormitoryInspectionActivity> {
	public static final DormitoryInspectionActivity dao = new DormitoryInspectionActivity().dao();
}
