package com.mht.common.model;

import com.mht.common.model.base.BaseDormitoryAdjustTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DormitoryAdjustTemp extends BaseDormitoryAdjustTemp<DormitoryAdjustTemp> {
	public static final DormitoryAdjustTemp dao = new DormitoryAdjustTemp().dao();
}
