package com.mht.common.model;

import com.mht.common.model.base.BaseEnrollMiddleSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnrollMiddleSchool extends BaseEnrollMiddleSchool<EnrollMiddleSchool> {
	public static final EnrollMiddleSchool dao = new EnrollMiddleSchool().dao();
}
