package com.mht.common.model;

import com.mht.common.model.base.BaseEnrollKindergarten;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnrollKindergarten extends BaseEnrollKindergarten<EnrollKindergarten> {
	public static final EnrollKindergarten dao = new EnrollKindergarten().dao();
}
