package com.mht.common.model;

import com.mht.common.model.base.BaseEnrollPrimarySchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnrollPrimarySchool extends BaseEnrollPrimarySchool<EnrollPrimarySchool> {
	public static final EnrollPrimarySchool dao = new EnrollPrimarySchool().dao();
}
