package com.mht.common.model;

import com.mht.common.model.base.BaseFastMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FastMenu extends BaseFastMenu<FastMenu> {
	public static final FastMenu dao = new FastMenu().dao();
}
