package com.mht.common.model;

import com.mht.common.model.base.BaseFleamarketAa99;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FleamarketAa99 extends BaseFleamarketAa99<FleamarketAa99> {
	public static final FleamarketAa99 dao = new FleamarketAa99().dao();
}
