package com.mht.common.model;

import com.mht.common.model.base.BaseFleamarketAa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FleamarketAa01 extends BaseFleamarketAa01<FleamarketAa01> {
	public static final FleamarketAa01 dao = new FleamarketAa01().dao();
}
