package com.mht.common.model;

import com.mht.common.model.base.BaseFleamarketAa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FleamarketAa02 extends BaseFleamarketAa02<FleamarketAa02> {
	public static final FleamarketAa02 dao = new FleamarketAa02().dao();
}
