package com.mht.common.model;

import com.mht.common.model.base.BaseLostfoundAa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LostfoundAa02 extends BaseLostfoundAa02<LostfoundAa02> {
	public static final LostfoundAa02 dao = new LostfoundAa02().dao();
}
