package com.mht.common.model;

import com.mht.common.model.base.BaseLostfoundAa99;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LostfoundAa99 extends BaseLostfoundAa99<LostfoundAa99> {
	public static final LostfoundAa99 dao = new LostfoundAa99().dao();
}
