package com.mht.common.model;

import com.mht.common.model.base.BaseLostfoundAa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LostfoundAa01 extends BaseLostfoundAa01<LostfoundAa01> {
	public static final LostfoundAa01 dao = new LostfoundAa01().dao();
}
