package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsOutStorage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsOutStorage extends BaseMaterialsOutStorage<MaterialsOutStorage> {
	public static final MaterialsOutStorage dao = new MaterialsOutStorage().dao();
}
