package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsDispatchDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsDispatchDetails extends BaseMaterialsDispatchDetails<MaterialsDispatchDetails> {
	public static final MaterialsDispatchDetails dao = new MaterialsDispatchDetails().dao();
}
