package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsPurchaseDetailsCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsPurchaseDetailsCourse extends BaseMaterialsPurchaseDetailsCourse<MaterialsPurchaseDetailsCourse> {
	public static final MaterialsPurchaseDetailsCourse dao = new MaterialsPurchaseDetailsCourse().dao();
}
