package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsManufacturersType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsManufacturersType extends BaseMaterialsManufacturersType<MaterialsManufacturersType> {
	public static final MaterialsManufacturersType dao = new MaterialsManufacturersType().dao();
}
