package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsPurchaseArrive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsPurchaseArrive extends BaseMaterialsPurchaseArrive<MaterialsPurchaseArrive> {
	public static final MaterialsPurchaseArrive dao = new MaterialsPurchaseArrive().dao();
}
