package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsInfoTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsInfoTemp extends BaseMaterialsInfoTemp<MaterialsInfoTemp> {
	public static final MaterialsInfoTemp dao = new MaterialsInfoTemp().dao();
}
