package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsReturnedGoodsDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsReturnedGoodsDetails extends BaseMaterialsReturnedGoodsDetails<MaterialsReturnedGoodsDetails> {
	public static final MaterialsReturnedGoodsDetails dao = new MaterialsReturnedGoodsDetails().dao();
}
