package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsGroup extends BaseMaterialsGroup<MaterialsGroup> {
	public static final MaterialsGroup dao = new MaterialsGroup().dao();
}
