package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsPurchaseDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsPurchaseDetails extends BaseMaterialsPurchaseDetails<MaterialsPurchaseDetails> {
	public static final MaterialsPurchaseDetails dao = new MaterialsPurchaseDetails().dao();
}
