package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsDispatchArrive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsDispatchArrive extends BaseMaterialsDispatchArrive<MaterialsDispatchArrive> {
	public static final MaterialsDispatchArrive dao = new MaterialsDispatchArrive().dao();
}
