package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsAttrValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsAttrValue extends BaseMaterialsAttrValue<MaterialsAttrValue> {
	public static final MaterialsAttrValue dao = new MaterialsAttrValue().dao();
}
