package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsSettlementRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsSettlementRecord extends BaseMaterialsSettlementRecord<MaterialsSettlementRecord> {
	public static final MaterialsSettlementRecord dao = new MaterialsSettlementRecord().dao();
}
