package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsDispatchExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsDispatchExtend extends BaseMaterialsDispatchExtend<MaterialsDispatchExtend> {
	public static final MaterialsDispatchExtend dao = new MaterialsDispatchExtend().dao();
}
