package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsDispatchBills;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsDispatchBills extends BaseMaterialsDispatchBills<MaterialsDispatchBills> {
	public static final MaterialsDispatchBills dao = new MaterialsDispatchBills().dao();
}
