package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialRecovery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialRecovery extends BaseMaterialRecovery<MaterialRecovery> {
	public static final MaterialRecovery dao = new MaterialRecovery().dao();
}
