package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsPurchaseBills;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsPurchaseBills extends BaseMaterialsPurchaseBills<MaterialsPurchaseBills> {
	public static final MaterialsPurchaseBills dao = new MaterialsPurchaseBills().dao();
}
