package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsPurchaseExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsPurchaseExtend extends BaseMaterialsPurchaseExtend<MaterialsPurchaseExtend> {
	public static final MaterialsPurchaseExtend dao = new MaterialsPurchaseExtend().dao();
}
