package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsPrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsPrice extends BaseMaterialsPrice<MaterialsPrice> {
	public static final MaterialsPrice dao = new MaterialsPrice().dao();
}
