package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsPurchasePriceManege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsPurchasePriceManege extends BaseMaterialsPurchasePriceManege<MaterialsPurchasePriceManege> {
	public static final MaterialsPurchasePriceManege dao = new MaterialsPurchasePriceManege().dao();
}
