package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsInfo extends BaseMaterialsInfo<MaterialsInfo> {
	public static final MaterialsInfo dao = new MaterialsInfo().dao();
}
