package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsAttrValueList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsAttrValueList extends BaseMaterialsAttrValueList<MaterialsAttrValueList> {
	public static final MaterialsAttrValueList dao = new MaterialsAttrValueList().dao();
}
