package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsManufacturers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsManufacturers extends BaseMaterialsManufacturers<MaterialsManufacturers> {
	public static final MaterialsManufacturers dao = new MaterialsManufacturers().dao();
}
