package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsApplyPriceManage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsApplyPriceManage extends BaseMaterialsApplyPriceManage<MaterialsApplyPriceManage> {
	public static final MaterialsApplyPriceManage dao = new MaterialsApplyPriceManage().dao();
}
