package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsReturnedGoodsBills;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsReturnedGoodsBills extends BaseMaterialsReturnedGoodsBills<MaterialsReturnedGoodsBills> {
	public static final MaterialsReturnedGoodsBills dao = new MaterialsReturnedGoodsBills().dao();
}
