package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsClass extends BaseMaterialsClass<MaterialsClass> {
	public static final MaterialsClass dao = new MaterialsClass().dao();
}
