package com.mht.common.model;

import com.mht.common.model.base.BaseMaterialsAttr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialsAttr extends BaseMaterialsAttr<MaterialsAttr> {
	public static final MaterialsAttr dao = new MaterialsAttr().dao();
}
