package com.mht.common.model;

import com.mht.common.model.base.BaseMiddleSchoolType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MiddleSchoolType extends BaseMiddleSchoolType<MiddleSchoolType> {
	public static final MiddleSchoolType dao = new MiddleSchoolType().dao();
}
