package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPacesetter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPacesetter extends BasePersonnelPacesetter<PersonnelPacesetter> {
	public static final PersonnelPacesetter dao = new PersonnelPacesetter().dao();
}
