package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelRecruitPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelRecruitPlan extends BasePersonnelRecruitPlan<PersonnelRecruitPlan> {
	public static final PersonnelRecruitPlan dao = new PersonnelRecruitPlan().dao();
}
