package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostTemp extends BasePersonnelPostTemp<PersonnelPostTemp> {
	public static final PersonnelPostTemp dao = new PersonnelPostTemp().dao();
}
