package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSocialSecurityDetailTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSocialSecurityDetailTemp extends BasePersonnelSocialSecurityDetailTemp<PersonnelSocialSecurityDetailTemp> {
	public static final PersonnelSocialSecurityDetailTemp dao = new PersonnelSocialSecurityDetailTemp().dao();
}
