package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSalaryAble;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSalaryAble extends BasePersonnelSalaryAble<PersonnelSalaryAble> {
	public static final PersonnelSalaryAble dao = new PersonnelSalaryAble().dao();
}
