package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPost extends BasePersonnelPost<PersonnelPost> {
	public static final PersonnelPost dao = new PersonnelPost().dao();
}
