package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelCertificate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelCertificate extends BasePersonnelCertificate<PersonnelCertificate> {
	public static final PersonnelCertificate dao = new PersonnelCertificate().dao();
}
