package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSocialSecurityTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSocialSecurityTemp extends BasePersonnelSocialSecurityTemp<PersonnelSocialSecurityTemp> {
	public static final PersonnelSocialSecurityTemp dao = new PersonnelSocialSecurityTemp().dao();
}
