package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelEmployeesRecordTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelEmployeesRecordTemp extends BasePersonnelEmployeesRecordTemp<PersonnelEmployeesRecordTemp> {
	public static final PersonnelEmployeesRecordTemp dao = new PersonnelEmployeesRecordTemp().dao();
}
