package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostPromotionSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostPromotionSetting extends BasePersonnelPostPromotionSetting<PersonnelPostPromotionSetting> {
	public static final PersonnelPostPromotionSetting dao = new PersonnelPostPromotionSetting().dao();
}
