package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelRuleCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelRuleCategory extends BasePersonnelRuleCategory<PersonnelRuleCategory> {
	public static final PersonnelRuleCategory dao = new PersonnelRuleCategory().dao();
}
