package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostSalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostSalary extends BasePersonnelPostSalary<PersonnelPostSalary> {
	public static final PersonnelPostSalary dao = new PersonnelPostSalary().dao();
}
