package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelFile extends BasePersonnelFile<PersonnelFile> {
	public static final PersonnelFile dao = new PersonnelFile().dao();
}
