package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelContractTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelContractTemp extends BasePersonnelContractTemp<PersonnelContractTemp> {
	public static final PersonnelContractTemp dao = new PersonnelContractTemp().dao();
}
