package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelRecruitChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelRecruitChannel extends BasePersonnelRecruitChannel<PersonnelRecruitChannel> {
	public static final PersonnelRecruitChannel dao = new PersonnelRecruitChannel().dao();
}
