package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelEmployeeInformationTemporary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelEmployeeInformationTemporary extends BasePersonnelEmployeeInformationTemporary<PersonnelEmployeeInformationTemporary> {
	public static final PersonnelEmployeeInformationTemporary dao = new PersonnelEmployeeInformationTemporary().dao();
}
