package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelAnnualBonusApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelAnnualBonusApply extends BasePersonnelAnnualBonusApply<PersonnelAnnualBonusApply> {
	public static final PersonnelAnnualBonusApply dao = new PersonnelAnnualBonusApply().dao();
}
