package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelBlackList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelBlackList extends BasePersonnelBlackList<PersonnelBlackList> {
	public static final PersonnelBlackList dao = new PersonnelBlackList().dao();
}
