package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPerformanceOvertimeApplyTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPerformanceOvertimeApplyTemp extends BasePersonnelPerformanceOvertimeApplyTemp<PersonnelPerformanceOvertimeApplyTemp> {
	public static final PersonnelPerformanceOvertimeApplyTemp dao = new PersonnelPerformanceOvertimeApplyTemp().dao();
}
