package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostGradingTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostGradingTemp extends BasePersonnelPostGradingTemp<PersonnelPostGradingTemp> {
	public static final PersonnelPostGradingTemp dao = new PersonnelPostGradingTemp().dao();
}
