package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPromotion extends BasePersonnelPromotion<PersonnelPromotion> {
	public static final PersonnelPromotion dao = new PersonnelPromotion().dao();
}
