package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSocialSecurityDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSocialSecurityDetail extends BasePersonnelSocialSecurityDetail<PersonnelSocialSecurityDetail> {
	public static final PersonnelSocialSecurityDetail dao = new PersonnelSocialSecurityDetail().dao();
}
