package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPacesetterTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPacesetterTemp extends BasePersonnelPacesetterTemp<PersonnelPacesetterTemp> {
	public static final PersonnelPacesetterTemp dao = new PersonnelPacesetterTemp().dao();
}
