package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelRule extends BasePersonnelRule<PersonnelRule> {
	public static final PersonnelRule dao = new PersonnelRule().dao();
}
