package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelEmpBlacklist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelEmpBlacklist extends BasePersonnelEmpBlacklist<PersonnelEmpBlacklist> {
	public static final PersonnelEmpBlacklist dao = new PersonnelEmpBlacklist().dao();
}
