package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelRetireManagement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelRetireManagement extends BasePersonnelRetireManagement<PersonnelRetireManagement> {
	public static final PersonnelRetireManagement dao = new PersonnelRetireManagement().dao();
}
