package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelAnnualAssessment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelAnnualAssessment extends BasePersonnelAnnualAssessment<PersonnelAnnualAssessment> {
	public static final PersonnelAnnualAssessment dao = new PersonnelAnnualAssessment().dao();
}
