package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelEmployeesRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelEmployeesRecord extends BasePersonnelEmployeesRecord<PersonnelEmployeesRecord> {
	public static final PersonnelEmployeesRecord dao = new PersonnelEmployeesRecord().dao();
}
