package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSubsidyDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSubsidyDetail extends BasePersonnelSubsidyDetail<PersonnelSubsidyDetail> {
	public static final PersonnelSubsidyDetail dao = new PersonnelSubsidyDetail().dao();
}
