package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelEmployeeInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelEmployeeInformation extends BasePersonnelEmployeeInformation<PersonnelEmployeeInformation> {
	public static final PersonnelEmployeeInformation dao = new PersonnelEmployeeInformation().dao();
}
