package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelAnnualBonusApplyTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelAnnualBonusApplyTemp extends BasePersonnelAnnualBonusApplyTemp<PersonnelAnnualBonusApplyTemp> {
	public static final PersonnelAnnualBonusApplyTemp dao = new PersonnelAnnualBonusApplyTemp().dao();
}
