package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelChangeRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelChangeRecord extends BasePersonnelChangeRecord<PersonnelChangeRecord> {
	public static final PersonnelChangeRecord dao = new PersonnelChangeRecord().dao();
}
