package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelApplicantInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelApplicantInfo extends BasePersonnelApplicantInfo<PersonnelApplicantInfo> {
	public static final PersonnelApplicantInfo dao = new PersonnelApplicantInfo().dao();
}
