package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelEmpBlacklistTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelEmpBlacklistTemp extends BasePersonnelEmpBlacklistTemp<PersonnelEmpBlacklistTemp> {
	public static final PersonnelEmpBlacklistTemp dao = new PersonnelEmpBlacklistTemp().dao();
}
