package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSocialSecurityPersonDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSocialSecurityPersonDetail extends BasePersonnelSocialSecurityPersonDetail<PersonnelSocialSecurityPersonDetail> {
	public static final PersonnelSocialSecurityPersonDetail dao = new PersonnelSocialSecurityPersonDetail().dao();
}
