package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostEstablishment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostEstablishment extends BasePersonnelPostEstablishment<PersonnelPostEstablishment> {
	public static final PersonnelPostEstablishment dao = new PersonnelPostEstablishment().dao();
}
