package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSecondCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSecondCode extends BasePersonnelSecondCode<PersonnelSecondCode> {
	public static final PersonnelSecondCode dao = new PersonnelSecondCode().dao();
}
