package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostPromotionStandard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostPromotionStandard extends BasePersonnelPostPromotionStandard<PersonnelPostPromotionStandard> {
	public static final PersonnelPostPromotionStandard dao = new PersonnelPostPromotionStandard().dao();
}
