package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSeniorityAllowanceStandard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSeniorityAllowanceStandard extends BasePersonnelSeniorityAllowanceStandard<PersonnelSeniorityAllowanceStandard> {
	public static final PersonnelSeniorityAllowanceStandard dao = new PersonnelSeniorityAllowanceStandard().dao();
}
