package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostChangeTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostChangeTemp extends BasePersonnelPostChangeTemp<PersonnelPostChangeTemp> {
	public static final PersonnelPostChangeTemp dao = new PersonnelPostChangeTemp().dao();
}
