package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostAdjustApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostAdjustApply extends BasePersonnelPostAdjustApply<PersonnelPostAdjustApply> {
	public static final PersonnelPostAdjustApply dao = new PersonnelPostAdjustApply().dao();
}
