package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelStaffInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelStaffInfo extends BasePersonnelStaffInfo<PersonnelStaffInfo> {
	public static final PersonnelStaffInfo dao = new PersonnelStaffInfo().dao();
}
