package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSenioritySalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSenioritySalary extends BasePersonnelSenioritySalary<PersonnelSenioritySalary> {
	public static final PersonnelSenioritySalary dao = new PersonnelSenioritySalary().dao();
}
