package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSocialSecurity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSocialSecurity extends BasePersonnelSocialSecurity<PersonnelSocialSecurity> {
	public static final PersonnelSocialSecurity dao = new PersonnelSocialSecurity().dao();
}
