package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelWorkInjuryRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelWorkInjuryRecord extends BasePersonnelWorkInjuryRecord<PersonnelWorkInjuryRecord> {
	public static final PersonnelWorkInjuryRecord dao = new PersonnelWorkInjuryRecord().dao();
}
