package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostLevelSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostLevelSetting extends BasePersonnelPostLevelSetting<PersonnelPostLevelSetting> {
	public static final PersonnelPostLevelSetting dao = new PersonnelPostLevelSetting().dao();
}
