package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSubsidy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSubsidy extends BasePersonnelSubsidy<PersonnelSubsidy> {
	public static final PersonnelSubsidy dao = new PersonnelSubsidy().dao();
}
