package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSalaryAbleTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSalaryAbleTemp extends BasePersonnelSalaryAbleTemp<PersonnelSalaryAbleTemp> {
	public static final PersonnelSalaryAbleTemp dao = new PersonnelSalaryAbleTemp().dao();
}
