package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelEducationAllowanceStandard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelEducationAllowanceStandard extends BasePersonnelEducationAllowanceStandard<PersonnelEducationAllowanceStandard> {
	public static final PersonnelEducationAllowanceStandard dao = new PersonnelEducationAllowanceStandard().dao();
}
