package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPerformanceOvertimeApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPerformanceOvertimeApply extends BasePersonnelPerformanceOvertimeApply<PersonnelPerformanceOvertimeApply> {
	public static final PersonnelPerformanceOvertimeApply dao = new PersonnelPerformanceOvertimeApply().dao();
}
