package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelStaffLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelStaffLevel extends BasePersonnelStaffLevel<PersonnelStaffLevel> {
	public static final PersonnelStaffLevel dao = new PersonnelStaffLevel().dao();
}
