package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPromote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPromote extends BasePersonnelPromote<PersonnelPromote> {
	public static final PersonnelPromote dao = new PersonnelPromote().dao();
}
