package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelHealthCondition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelHealthCondition extends BasePersonnelHealthCondition<PersonnelHealthCondition> {
	public static final PersonnelHealthCondition dao = new PersonnelHealthCondition().dao();
}
