package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelAnnualAssessmentTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelAnnualAssessmentTemp extends BasePersonnelAnnualAssessmentTemp<PersonnelAnnualAssessmentTemp> {
	public static final PersonnelAnnualAssessmentTemp dao = new PersonnelAnnualAssessmentTemp().dao();
}
