package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostChange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostChange extends BasePersonnelPostChange<PersonnelPostChange> {
	public static final PersonnelPostChange dao = new PersonnelPostChange().dao();
}
