package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelCode extends BasePersonnelCode<PersonnelCode> {
	public static final PersonnelCode dao = new PersonnelCode().dao();
}
