package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelSocialSecurityEnter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelSocialSecurityEnter extends BasePersonnelSocialSecurityEnter<PersonnelSocialSecurityEnter> {
	public static final PersonnelSocialSecurityEnter dao = new PersonnelSocialSecurityEnter().dao();
}
