package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelTechnologyAllowanceStandard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelTechnologyAllowanceStandard extends BasePersonnelTechnologyAllowanceStandard<PersonnelTechnologyAllowanceStandard> {
	public static final PersonnelTechnologyAllowanceStandard dao = new PersonnelTechnologyAllowanceStandard().dao();
}
