package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostApply extends BasePersonnelPostApply<PersonnelPostApply> {
	public static final PersonnelPostApply dao = new PersonnelPostApply().dao();
}
