package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelContractChange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelContractChange extends BasePersonnelContractChange<PersonnelContractChange> {
	public static final PersonnelContractChange dao = new PersonnelContractChange().dao();
}
