package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostGrading;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostGrading extends BasePersonnelPostGrading<PersonnelPostGrading> {
	public static final PersonnelPostGrading dao = new PersonnelPostGrading().dao();
}
