package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelPostApplyAuditRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelPostApplyAuditRecord extends BasePersonnelPostApplyAuditRecord<PersonnelPostApplyAuditRecord> {
	public static final PersonnelPostApplyAuditRecord dao = new PersonnelPostApplyAuditRecord().dao();
}
