package com.mht.common.model;

import com.mht.common.model.base.BasePersonnelLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelLeave extends BasePersonnelLeave<PersonnelLeave> {
	public static final PersonnelLeave dao = new PersonnelLeave().dao();
}
