package com.mht.common.model;

import com.mht.common.model.base.BasePmDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmDetail extends BasePmDetail<PmDetail> {
	public static final PmDetail dao = new PmDetail().dao();
}
