package com.mht.common.model;

import com.mht.common.model.base.BasePmField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmField extends BasePmField<PmField> {
	public static final PmField dao = new PmField().dao();
}
