package com.mht.common.model;

import com.mht.common.model.base.BasePmIndex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmIndex extends BasePmIndex<PmIndex> {
	public static final PmIndex dao = new PmIndex().dao();
}
