package com.mht.common.model;

import com.mht.common.model.base.BasePmLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmLink extends BasePmLink<PmLink> {
	public static final PmLink dao = new PmLink().dao();
}
