package com.mht.common.model;

import com.mht.common.model.base.BasePmModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmModule extends BasePmModule<PmModule> {
	public static final PmModule dao = new PmModule().dao();
}
