package com.mht.common.model;

import com.mht.common.model.base.BasePmTableJoin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmTableJoin extends BasePmTableJoin<PmTableJoin> {
	public static final PmTableJoin dao = new PmTableJoin().dao();
}
