package com.mht.common.model;

import com.mht.common.model.base.BasePmTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmTable extends BasePmTable<PmTable> {
	public static final PmTable dao = new PmTable().dao();
}
