package com.mht.common.model;

import com.mht.common.model.base.BasePropertyAa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropertyAa02 extends BasePropertyAa02<PropertyAa02> {
	public static final PropertyAa02 dao = new PropertyAa02().dao();
}
