package com.mht.common.model;

import com.mht.common.model.base.BasePropertyAb01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropertyAb01 extends BasePropertyAb01<PropertyAb01> {
	public static final PropertyAb01 dao = new PropertyAb01().dao();
}
