package com.mht.common.model;

import com.mht.common.model.base.BasePropertyAa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropertyAa01 extends BasePropertyAa01<PropertyAa01> {
	public static final PropertyAa01 dao = new PropertyAa01().dao();
}
