package com.mht.common.model;

import com.mht.common.model.base.BasePropertyAa99;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropertyAa99 extends BasePropertyAa99<PropertyAa99> {
	public static final PropertyAa99 dao = new PropertyAa99().dao();
}
