package com.mht.common.model;

import com.mht.common.model.base.BasePropertyBa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropertyBa02 extends BasePropertyBa02<PropertyBa02> {
	public static final PropertyBa02 dao = new PropertyBa02().dao();
}
