package com.mht.common.model;

import com.mht.common.model.base.BasePubCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PubCountry extends BasePubCountry<PubCountry> {
	public static final PubCountry dao = new PubCountry().dao();
}
