package com.mht.common.model;

import com.mht.common.model.base.BasePubCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PubCity extends BasePubCity<PubCity> {
	public static final PubCity dao = new PubCity().dao();
}
