package com.mht.common.model;

import com.mht.common.model.base.BasePubEduLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PubEduLevel extends BasePubEduLevel<PubEduLevel> {
	public static final PubEduLevel dao = new PubEduLevel().dao();
}
