package com.mht.common.model;

import com.mht.common.model.base.BasePubNation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PubNation extends BasePubNation<PubNation> {
	public static final PubNation dao = new PubNation().dao();
}
