package com.mht.common.model;

import com.mht.common.model.base.BasePubProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PubProvince extends BasePubProvince<PubProvince> {
	public static final PubProvince dao = new PubProvince().dao();
}
