package com.mht.common.model;

import com.mht.common.model.base.BasePubTown;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PubTown extends BasePubTown<PubTown> {
	public static final PubTown dao = new PubTown().dao();
}
