package com.mht.common.model;

import com.mht.common.model.base.BasePxAudit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxAudit extends BasePxAudit<PxAudit> {
	public static final PxAudit dao = new PxAudit().dao();
}
