package com.mht.common.model;

import com.mht.common.model.base.BasePxCertificateSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxCertificateSetting extends BasePxCertificateSetting<PxCertificateSetting> {
	public static final PxCertificateSetting dao = new PxCertificateSetting().dao();
}
