package com.mht.common.model;

import com.mht.common.model.base.BasePxCertificateApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxCertificateApply extends BasePxCertificateApply<PxCertificateApply> {
	public static final PxCertificateApply dao = new PxCertificateApply().dao();
}
