package com.mht.common.model;

import com.mht.common.model.base.BasePxCertificateClaim;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxCertificateClaim extends BasePxCertificateClaim<PxCertificateClaim> {
	public static final PxCertificateClaim dao = new PxCertificateClaim().dao();
}
