package com.mht.common.model;

import com.mht.common.model.base.BasePxCertificatePrint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxCertificatePrint extends BasePxCertificatePrint<PxCertificatePrint> {
	public static final PxCertificatePrint dao = new PxCertificatePrint().dao();
}
