package com.mht.common.model;

import com.mht.common.model.base.BasePxChargeFiling;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxChargeFiling extends BasePxChargeFiling<PxChargeFiling> {
	public static final PxChargeFiling dao = new PxChargeFiling().dao();
}
