package com.mht.common.model;

import com.mht.common.model.base.BasePxClassCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxClassCourse extends BasePxClassCourse<PxClassCourse> {
	public static final PxClassCourse dao = new PxClassCourse().dao();
}
