package com.mht.common.model;

import com.mht.common.model.base.BasePxClassGraduation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxClassGraduation extends BasePxClassGraduation<PxClassGraduation> {
	public static final PxClassGraduation dao = new PxClassGraduation().dao();
}
