package com.mht.common.model;

import com.mht.common.model.base.BasePxClassTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxClassTeacher extends BasePxClassTeacher<PxClassTeacher> {
	public static final PxClassTeacher dao = new PxClassTeacher().dao();
}
