package com.mht.common.model;

import com.mht.common.model.base.BasePxClassroom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxClassroom extends BasePxClassroom<PxClassroom> {
	public static final PxClassroom dao = new PxClassroom().dao();
}
