package com.mht.common.model;

import com.mht.common.model.base.BasePxClassSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxClassSchedule extends BasePxClassSchedule<PxClassSchedule> {
	public static final PxClassSchedule dao = new PxClassSchedule().dao();
}
