package com.mht.common.model;

import com.mht.common.model.base.BasePxCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxCourse extends BasePxCourse<PxCourse> {
	public static final PxCourse dao = new PxCourse().dao();
}
