package com.mht.common.model;

import com.mht.common.model.base.BasePxCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxCode extends BasePxCode<PxCode> {
	public static final PxCode dao = new PxCode().dao();
}
