package com.mht.common.model;

import com.mht.common.model.base.BasePxExamRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxExamRecord extends BasePxExamRecord<PxExamRecord> {
	public static final PxExamRecord dao = new PxExamRecord().dao();
}
