package com.mht.common.model;

import com.mht.common.model.base.BasePxExamAssess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxExamAssess extends BasePxExamAssess<PxExamAssess> {
	public static final PxExamAssess dao = new PxExamAssess().dao();
}
