package com.mht.common.model;

import com.mht.common.model.base.BasePxLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxLog extends BasePxLog<PxLog> {
	public static final PxLog dao = new PxLog().dao();
}
