package com.mht.common.model;

import com.mht.common.model.base.BasePxPapers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxPapers extends BasePxPapers<PxPapers> {
	public static final PxPapers dao = new PxPapers().dao();
}
