package com.mht.common.model;

import com.mht.common.model.base.BasePxPayRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxPayRecord extends BasePxPayRecord<PxPayRecord> {
	public static final PxPayRecord dao = new PxPayRecord().dao();
}
