package com.mht.common.model;

import com.mht.common.model.base.BasePxPersonalTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxPersonalTest extends BasePxPersonalTest<PxPersonalTest> {
	public static final PxPersonalTest dao = new PxPersonalTest().dao();
}
