package com.mht.common.model;

import com.mht.common.model.base.BasePxPost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxPost extends BasePxPost<PxPost> {
	public static final PxPost dao = new PxPost().dao();
}
