package com.mht.common.model;

import com.mht.common.model.base.BasePxProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxProject extends BasePxProject<PxProject> {
	public static final PxProject dao = new PxProject().dao();
}
