package com.mht.common.model;

import com.mht.common.model.base.BasePxSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxSchool extends BasePxSchool<PxSchool> {
	public static final PxSchool dao = new PxSchool().dao();
}
