package com.mht.common.model;

import com.mht.common.model.base.BasePxSchoolroom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxSchoolroom extends BasePxSchoolroom<PxSchoolroom> {
	public static final PxSchoolroom dao = new PxSchoolroom().dao();
}
