package com.mht.common.model;

import com.mht.common.model.base.BasePxSchoolSysuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxSchoolSysuser extends BasePxSchoolSysuser<PxSchoolSysuser> {
	public static final PxSchoolSysuser dao = new PxSchoolSysuser().dao();
}
