package com.mht.common.model;

import com.mht.common.model.base.BasePxSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxSetting extends BasePxSetting<PxSetting> {
	public static final PxSetting dao = new PxSetting().dao();
}
