package com.mht.common.model;

import com.mht.common.model.base.BasePxStudentStudy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxStudentStudy extends BasePxStudentStudy<PxStudentStudy> {
	public static final PxStudentStudy dao = new PxStudentStudy().dao();
}
