package com.mht.common.model;

import com.mht.common.model.base.BasePxStudentEnroll;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxStudentEnroll extends BasePxStudentEnroll<PxStudentEnroll> {
	public static final PxStudentEnroll dao = new PxStudentEnroll().dao();
}
