package com.mht.common.model;

import com.mht.common.model.base.BasePxStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxStudent extends BasePxStudent<PxStudent> {
	public static final PxStudent dao = new PxStudent().dao();
}
