package com.mht.common.model;

import com.mht.common.model.base.BasePxStudentGraduation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxStudentGraduation extends BasePxStudentGraduation<PxStudentGraduation> {
	public static final PxStudentGraduation dao = new PxStudentGraduation().dao();
}
