package com.mht.common.model;

import com.mht.common.model.base.BasePxStudentEnrollTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxStudentEnrollTemp extends BasePxStudentEnrollTemp<PxStudentEnrollTemp> {
	public static final PxStudentEnrollTemp dao = new PxStudentEnrollTemp().dao();
}
