package com.mht.common.model;

import com.mht.common.model.base.BasePxTestQuestionTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxTestQuestionTemp extends BasePxTestQuestionTemp<PxTestQuestionTemp> {
	public static final PxTestQuestionTemp dao = new PxTestQuestionTemp().dao();
}
