package com.mht.common.model;

import com.mht.common.model.base.BasePxTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxTeacher extends BasePxTeacher<PxTeacher> {
	public static final PxTeacher dao = new PxTeacher().dao();
}
