package com.mht.common.model;

import com.mht.common.model.base.BasePxTestQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxTestQuestion extends BasePxTestQuestion<PxTestQuestion> {
	public static final PxTestQuestion dao = new PxTestQuestion().dao();
}
