package com.mht.common.model;

import com.mht.common.model.base.BasePxTrainplanApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PxTrainplanApply extends BasePxTrainplanApply<PxTrainplanApply> {
	public static final PxTrainplanApply dao = new PxTrainplanApply().dao();
}
