package com.mht.common.model;

import com.mht.common.model.base.BaseReturnZoneMaterialsDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnZoneMaterialsDetails extends BaseReturnZoneMaterialsDetails<ReturnZoneMaterialsDetails> {
	public static final ReturnZoneMaterialsDetails dao = new ReturnZoneMaterialsDetails().dao();
}
