package com.mht.common.model;

import com.mht.common.model.base.BaseReturnZoneMaterialsBills;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnZoneMaterialsBills extends BaseReturnZoneMaterialsBills<ReturnZoneMaterialsBills> {
	public static final ReturnZoneMaterialsBills dao = new ReturnZoneMaterialsBills().dao();
}
