package com.mht.common.model;

import com.mht.common.model.base.BaseReturnZoneExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnZoneExtend extends BaseReturnZoneExtend<ReturnZoneExtend> {
	public static final ReturnZoneExtend dao = new ReturnZoneExtend().dao();
}
