package com.mht.common.model;

import com.mht.common.model.base.BaseReturnZoneMaterialsArrive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnZoneMaterialsArrive extends BaseReturnZoneMaterialsArrive<ReturnZoneMaterialsArrive> {
	public static final ReturnZoneMaterialsArrive dao = new ReturnZoneMaterialsArrive().dao();
}
