package com.mht.common.model;

import com.mht.common.model.base.BaseSchoolZone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchoolZone extends BaseSchoolZone<SchoolZone> {
	public static final SchoolZone dao = new SchoolZone().dao();
}
