package com.mht.common.model;

import com.mht.common.model.base.BaseSchoolArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchoolArea extends BaseSchoolArea<SchoolArea> {
	public static final SchoolArea dao = new SchoolArea().dao();
}
