package com.mht.common.model;

import com.mht.common.model.base.BaseSettingItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SettingItem extends BaseSettingItem<SettingItem> {
	public static final SettingItem dao = new SettingItem().dao();
}
