package com.mht.common.model;

import com.mht.common.model.base.BaseSiteInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SiteInfo extends BaseSiteInfo<SiteInfo> {
	public static final SiteInfo dao = new SiteInfo().dao();
}
