package com.mht.common.model;

import com.mht.common.model.base.BaseSmsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsInfo extends BaseSmsInfo<SmsInfo> {
	public static final SmsInfo dao = new SmsInfo().dao();
}
