package com.mht.common.model;

import com.mht.common.model.base.BaseSmsVerifyCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsVerifyCode extends BaseSmsVerifyCode<SmsVerifyCode> {
	public static final SmsVerifyCode dao = new SmsVerifyCode().dao();
}
