package com.mht.common.model;

import com.mht.common.model.base.BaseStudentReturnSchoolInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentReturnSchoolInfo extends BaseStudentReturnSchoolInfo<StudentReturnSchoolInfo> {
	public static final StudentReturnSchoolInfo dao = new StudentReturnSchoolInfo().dao();
}
