package com.mht.common.model;

import com.mht.common.model.base.BaseStuRetreats;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StuRetreats extends BaseStuRetreats<StuRetreats> {
	public static final StuRetreats dao = new StuRetreats().dao();
}
