package com.mht.common.model;

import com.mht.common.model.base.BaseSysCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysCode extends BaseSysCode<SysCode> {
	public static final SysCode dao = new SysCode().dao();
}
