package com.mht.common.model;

import com.mht.common.model.base.BaseSysModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysModule extends BaseSysModule<SysModule> {
	public static final SysModule dao = new SysModule().dao();
}
