package com.mht.common.model;

import com.mht.common.model.base.BaseSysPlat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPlat extends BaseSysPlat<SysPlat> {
	public static final SysPlat dao = new SysPlat().dao();
}
