package com.mht.common.model;

import com.mht.common.model.base.BaseSysPerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPerm extends BaseSysPerm<SysPerm> {
	public static final SysPerm dao = new SysPerm().dao();
}
