package com.mht.common.model;

import com.mht.common.model.base.BaseSysRoleSite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleSite extends BaseSysRoleSite<SysRoleSite> {
	public static final SysRoleSite dao = new SysRoleSite().dao();
}
