package com.mht.common.model;

import com.mht.common.model.base.BaseSysReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysReply extends BaseSysReply<SysReply> {
	public static final SysReply dao = new SysReply().dao();
}
