package com.mht.common.model;

import com.mht.common.model.base.BaseSysRolePerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRolePerm extends BaseSysRolePerm<SysRolePerm> {
	public static final SysRolePerm dao = new SysRolePerm().dao();
}
