package com.mht.common.model;

import com.mht.common.model.base.BaseSysSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSetting extends BaseSysSetting<SysSetting> {
	public static final SysSetting dao = new SysSetting().dao();
}
