package com.mht.common.model;

import com.mht.common.model.base.BaseSysUserPerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserPerm extends BaseSysUserPerm<SysUserPerm> {
	public static final SysUserPerm dao = new SysUserPerm().dao();
}
