package com.mht.common.model;

import com.mht.common.model.base.BaseTeacherReturnSchoolInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeacherReturnSchoolInfo extends BaseTeacherReturnSchoolInfo<TeacherReturnSchoolInfo> {
	public static final TeacherReturnSchoolInfo dao = new TeacherReturnSchoolInfo().dao();
}
