package com.mht.common.model;

import com.mht.common.model.base.BaseTmAa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmAa01 extends BaseTmAa01<TmAa01> {
	public static final TmAa01 dao = new TmAa01().dao();
}
