package com.mht.common.model;

import com.mht.common.model.base.BaseTmAa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmAa02 extends BaseTmAa02<TmAa02> {
	public static final TmAa02 dao = new TmAa02().dao();
}
