package com.mht.common.model;

import com.mht.common.model.base.BaseTmAa03;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmAa03 extends BaseTmAa03<TmAa03> {
	public static final TmAa03 dao = new TmAa03().dao();
}
