package com.mht.common.model;

import com.mht.common.model.base.BaseWeather;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Weather extends BaseWeather<Weather> {
	public static final Weather dao = new Weather().dao();
}
