package com.mht.common.model;

import com.mht.common.model.base.BaseWechatAa02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatAa02 extends BaseWechatAa02<WechatAa02> {
	public static final WechatAa02 dao = new WechatAa02().dao();
}
