package com.mht.common.model;

import com.mht.common.model.base.BaseWechatAa01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatAa01 extends BaseWechatAa01<WechatAa01> {
	public static final WechatAa01 dao = new WechatAa01().dao();
}
