package com.mht.common.model;

import com.mht.common.model.base.BaseWechatAa99;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatAa99 extends BaseWechatAa99<WechatAa99> {
	public static final WechatAa99 dao = new WechatAa99().dao();
}
