package com.mht.common.model;

import com.mht.common.model.base.BaseWxAccessToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxAccessToken extends BaseWxAccessToken<WxAccessToken> {
	public static final WxAccessToken dao = new WxAccessToken().dao();
}
