package com.mht.common.model;

import com.mht.common.model.base.BaseXimBrowseRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XimBrowseRecord extends BaseXimBrowseRecord<XimBrowseRecord> {
	public static final XimBrowseRecord dao = new XimBrowseRecord().dao();
}
