package com.mht.common.model;

import com.mht.common.model.base.BaseXimLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XimLoginLog extends BaseXimLoginLog<XimLoginLog> {
	public static final XimLoginLog dao = new XimLoginLog().dao();
}
