package com.mht.common.model;

import com.mht.common.model.base.BaseXimLibrary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XimLibrary extends BaseXimLibrary<XimLibrary> {
	public static final XimLibrary dao = new XimLibrary().dao();
}
