package com.mht.common.model;

import com.mht.common.model.base.BaseXimMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XimMenu extends BaseXimMenu<XimMenu> {
	public static final XimMenu dao = new XimMenu().dao();
}
