package com.mht.common.model;

import com.mht.common.model.base.BaseXimModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XimModel extends BaseXimModel<XimModel> {
	public static final XimModel dao = new XimModel().dao();
}
