package com.mht.common.model;

import com.mht.common.model.base.BaseXimQuesRelated;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XimQuesRelated extends BaseXimQuesRelated<XimQuesRelated> {
	public static final XimQuesRelated dao = new XimQuesRelated().dao();
}
