package com.mht.common.model;

import com.mht.common.model.base.BaseXimRoleMatch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XimRoleMatch extends BaseXimRoleMatch<XimRoleMatch> {
	public static final XimRoleMatch dao = new XimRoleMatch().dao();
}
