package com.mht.common.model;

import com.mht.common.model.base.BaseXimSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XimSetting extends BaseXimSetting<XimSetting> {
	public static final XimSetting dao = new XimSetting().dao();
}
