package com.mht.common.model;

import com.mht.common.model.base.BaseZoneMaterialsOutStockArrive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoneMaterialsOutStockArrive extends BaseZoneMaterialsOutStockArrive<ZoneMaterialsOutStockArrive> {
	public static final ZoneMaterialsOutStockArrive dao = new ZoneMaterialsOutStockArrive().dao();
}
