package com.mht.common.model;

import com.mht.common.model.base.BaseZoneMaterialsOutStockDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoneMaterialsOutStockDetails extends BaseZoneMaterialsOutStockDetails<ZoneMaterialsOutStockDetails> {
	public static final ZoneMaterialsOutStockDetails dao = new ZoneMaterialsOutStockDetails().dao();
}
