package com.mht.common.model;

import com.mht.common.model.base.BaseZoneOutExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoneOutExtend extends BaseZoneOutExtend<ZoneOutExtend> {
	public static final ZoneOutExtend dao = new ZoneOutExtend().dao();
}
