package com.mht.common.model;

import com.mht.common.model.base.BaseZoneMaterialsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoneMaterialsInfo extends BaseZoneMaterialsInfo<ZoneMaterialsInfo> {
	public static final ZoneMaterialsInfo dao = new ZoneMaterialsInfo().dao();
}
