package com.mht.common.model;

import com.mht.common.model.base.BaseZoneMaterialsOutStockBills;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoneMaterialsOutStockBills extends BaseZoneMaterialsOutStockBills<ZoneMaterialsOutStockBills> {
	public static final ZoneMaterialsOutStockBills dao = new ZoneMaterialsOutStockBills().dao();
}
